### ISSUE TITLE
 Undefined Projection: Albers

### ISSUE THREAD

**Issue by nickolanack** [proj4php/proj4php#122]
came across this wkt projection which throws an exception

```php 

include("vendor/autoload.php");

use proj4php\Proj4php;
use proj4php\Proj;
use proj4php\Point;

// Initialise Proj4
$proj4 = new Proj4php();


$example   = new Proj('PROJCS["NAD83_CSRS_BC_Albers",GEOGCS["GCS_NAD83(CSRS)",DATUM["D_North_American_1983_CSRS98",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Albers"],PARAMETER["standard_parallel_1",50],PARAMETER["standard_parallel_2",58.5],PARAMETER["latitude_of_origin",45],PARAMETER["central_meridian",-126],PARAMETER["false_easting",1000000],PARAMETER["false_northing",0],UNIT["Meter",1]]', $proj4);

```

```bash
Fatal error: Uncaught Exception: Undefined Projection: Albers in /Users/nblackwe/proj4/proj4php/src/Wkt.php:74
Stack trace:
#0 /Users/nblackwe/proj4/proj4php/src/Wkt.php(324): proj4php\Wkt::ParseRecursive('PROJECTION["Alb...', Object(stdClass))
#1 /Users/nblackwe/proj4/proj4php/src/Wkt.php(16): proj4php\Wkt::ParseRecursive('PROJCS["NAD83_C...')
#2 /Users/nblackwe/proj4/proj4php/src/Proj.php(198): proj4php\Wkt::Parse('PROJCS["NAD83_C...')
#3 /Users/nblackwe/proj4/proj4php/test.php(13): proj4php\Proj->__construct('PROJCS["NAD83_C...', Object(proj4php\Proj4php))
#4 {main}
  thrown in /Users/nblackwe/proj4/proj4php/src/Wkt.php on line 74

```

**Comment by nickolanack** [comment]
added to $wktProjections in wkt.php:
```php 
 self::$wktProjections["Albers"] = 'aea'; 
 ```
 
![Screen Shot 2022-02-04 at 1 48 17 PM](https://user-images.githubusercontent.com/8965209/152607762-aa9c7649-a7d9-4e09-b7b7-e20423779caf.png)
