### ISSUE TITLE
Error with WKT definition

### ISSUE THREAD

**Issue by sezeryalcin** [proj4php/proj4php#98]
I am just checking this out. I was trying to add a new projection but got some errors.

Definition data I got from:
https://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::8997
---------------------------
GEODCRS["ITRF2000",
  DATUM["International Terrestrial Reference Frame 2000",
    ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1.0]]],
  CS[ellipsoidal,2],
    AXIS["latitude",north,ORDER[1]],
    AXIS["longitude",east,ORDER[2]],
    ANGLEUNIT["degree",0.01745329252],
  ID["EPSG",8997]]
-------------------------------

And stacktrace:

PHP Fatal error:  Uncaught Exception: failed to load projection definition for: GEODCRS["ITRF2000", DATUM["INTERNATIONAL TERRESTRIAL REFERENCE FRAME 2000", ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["METRE",1.0]]], CS[ELLIPSOIDAL,2], AXIS["LATITUDE",NORTH,ORDER[1]], AXIS["LONGITUDE",EAST,ORDER[2]], ANGLEUNIT["DEGREE",0.01745329252], ID["EPSG",8997]] in /home/sezer/tmp2/proj4php/src/Proj4php.php:640
Stack trace:
#0 /home/sezer/tmp2/proj4php/src/Proj.php(350): proj4php\Proj4php::reportError('failed to load ...')
#1 /home/sezer/tmp2/proj4php/src/Proj.php(320): proj4php\Proj->defsFailed()
#2 /home/sezer/tmp2/proj4php/src/Proj.php(299): proj4php\Proj->loadFromService()
#3 /home/sezer/tmp2/proj4php/src/Proj.php(272): proj4php\Proj->loadProjDefinition()
#4 /home/sezer/tmp2/proj4php/test/testproj.php(18): proj4php\Proj->__construct('GEODCRS["ITRF20...', Object(proj4php\Proj4php))
#5 {main}
  thrown in /home/sezer/tmp2/proj4php/src/Proj4php.php on line 640

**Comment by julien2512** [comment]
Hi @sezeryalcin 

We already did the same with GEOGCS keywork.

Might you try the "issue98" branch with an unit test of your own ?
You can pull request on it inside test/Proj4phpTest.php:testInlineProjectionMethod2

Regards,

**Comment by sezeryalcin** [comment]
Ok, I am checking this now, will let you know.

**Comment by sezeryalcin** [comment]
This seems working on issue98. Is there a reason why this is not in master?

**Comment by julien2512** [comment]
The pull request is #99

**Comment by sezeryalcin** [comment]
Thank you, Ryu!
